language: node_js
node_js:
- '10'
install: npm install
cache:
  directories:
  - node_modules
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  keep-history: true
  api_key:
    secure: UqxF+++Tz9EJaRx8SNRXyMBHHr/DymWUb50VjF4W+nqj4+vdL47MogoKOeAp4urXA9srDJDLmQDEpNYttT6wd9Y/jM3Q9MDGTX8C13wbMqKOF9v14k3885Fwp+An59gAe4AiqBKJ7wT5YlXWZr0vRGrXE+ZbRvnmq2b/MfTuTeg5IorfapGDN+WqCvmzi9IwdmC5G2m8+ZH32zIr60FoUHFZ0UlEsOMvl3aacOeC9cSiWrjaCYBlICrJYqiw/5OJbZJ/zujy7iA2DG/JtHuscbdHVgsO79CYAyzeun/DsTEUM7nvgAXEwdinc/MPtE16rdFO/LW+lPqmy/lQ5xWPGvIB28ypRshCj683Kgpxo0HZU1Ts4F2zj2ISKsC2ky9PIayK2og/KPxMyXPjOzh9g2sbhD6r2OBlWBGT3aYqNstG4Zgk2lx3A/Pq1ix7/AUyHbI/uMKLhrUKZvQeupYbvSGzoSe+VtdVBQizrsPdrBWfw9+e1ORpzGd82rQIaWPzTozvrqFRkyQuAQ4GhSJ5mRF4o4waRMtNEHQooLF6VAcaSgqYGl4FCjZZ4gcFi8Y/GcZ6dvtxCNV8kWYsFQKrH2dW9ZCXvkhtgFBpoDqY/YfRIDcKZYcAeilM7s9dOkWTuJ6QjiDpk50WnBuqS/1BijGIrXYxkhmfQXcnWw4tMV0=
  app: movie-watchlister-api
  on:
    repo: saniochky/watchlist-api
    branch: main
    skip_cleanup: true
env:
  global:
    secure: A2f0FFdD86/a8oYsaUXlh5EXv/K55QGFg0Uh3I8Szfu0/lerpozDMTtv+ngPdGTfY+mhezBZEYHEae42XSG2/qdr//fqe3UoSyNJzihRTTwt1ieIiolu4MzKE0s8hZ1dE+CRVR5TE/FMVExozeJjy25mJEBbeCcsNIFhqbT3JpDEhDoRN5AdurKXHEwI5+UUb1ST/mw0HnX+vkMJHNoM0YjwqqkjGe/gjqe9VIhbamiXgRzwdSSJWDABiqaGP1HqRpOen8UsDwyqUZczOFUGcfDRgQB/S0oZLqC2AtDW+l6esZdnGmvPg90orItQnSGXuUWZfiBhvqQ2TSMXxbQbP7uaV6gOGTj8OMMPk1v2yAfxMWAbDqodb9J2AEp112vEr8JKWCU5JDTS41Ovix6nqkFGdIvTo2VFRMQnDg43YrdSBwVPatyEkPYAezd5tIHqW+GEKimY6nALC8FVZuIse5zg+Mhu0CGhdqk0/LmEkkdjyEJ4MXGZzSQ3rMIVqV/UFUpb/S32SU+AlVMICWRnB8FseYUiJl2PN7D7PZ9J6lugNETIV6VTaKu2xG+QxpzRWQnOSP7QHpDJYYKMjbDuPhAfKozVN7W2W2idz9oFUGDaMYokjSGbMLMRxMFySNXB7Ol5UDF4LNyPS+fqGFSrbbGB/JQuaU1omZu/tipLnsM=
