language: node_js
node_js:
- '10'
install: npm install
cache:
  directories:
  - node_modules
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  keep-history: true
  api_key:
    secure: U9GLSnUjPiM+AYVl6sB6WExn2s+KAkktdTh/lbseGQo7aLm46Fh5Jsmpei2/oYh9/pYBTkDcc7jEeiaGLYV4/Lqze+Lk6/UJF14ox9N1FSlfrDfcEXlzylaWO3JMIJSwoUYEN/g8U9x0OWHBA+OBdMzFfuI3QzATuwmbIZUH7IPSV+YeHHv+JiQqTXJHQNdz+ahL8EdTVctFMiv1vHRmBtooatzBDf1OyStUyCJWxnPQAMGall+Lu91fDyxv1I0a6PwiE/+wmPthzPU2dLQrXIUQrNjJoKx0OXyTxcUKY7omjMLKlj0EjtBtZnphPdqZe9m5D2d5olqB2IW6QQStr4YV+LofDxaN0CNqvEuF8N/LQqvJN+D79uNbrmeKjYX5E2bZfgg0UFZWSCItVjV65MYFLVXAc7H1NZrpFwM1u/j7zURMR9skiWeipNGjqJpjuHB7MwiXtR7CauyWAqnrmxMwghCPdFZ0lzOXe9u60jUPH39fgKcUiYcQH65y6/lYUcr+gpxV+sFdqk9emseMBXQKxtmEzchWkkw2I2UkUHsLQdKRmpjMhy+C6rWYCsHEyzmx+Eoz1C50wEyM+UVLTr3vBShQKkZXY5sEQbnxw73A/zt/nBDjNH8Cd7d2/WOgNsj99hDs8/PGU7OXp58PwS4VNR0lSt714gasoXqYeiY=
  app: movie-watchlister-api
  on:
    repo: saniochky/watchlist-api
    branch: main
    skip_cleanup: true
env:
  global:
    secure: A2f0FFdD86/a8oYsaUXlh5EXv/K55QGFg0Uh3I8Szfu0/lerpozDMTtv+ngPdGTfY+mhezBZEYHEae42XSG2/qdr//fqe3UoSyNJzihRTTwt1ieIiolu4MzKE0s8hZ1dE+CRVR5TE/FMVExozeJjy25mJEBbeCcsNIFhqbT3JpDEhDoRN5AdurKXHEwI5+UUb1ST/mw0HnX+vkMJHNoM0YjwqqkjGe/gjqe9VIhbamiXgRzwdSSJWDABiqaGP1HqRpOen8UsDwyqUZczOFUGcfDRgQB/S0oZLqC2AtDW+l6esZdnGmvPg90orItQnSGXuUWZfiBhvqQ2TSMXxbQbP7uaV6gOGTj8OMMPk1v2yAfxMWAbDqodb9J2AEp112vEr8JKWCU5JDTS41Ovix6nqkFGdIvTo2VFRMQnDg43YrdSBwVPatyEkPYAezd5tIHqW+GEKimY6nALC8FVZuIse5zg+Mhu0CGhdqk0/LmEkkdjyEJ4MXGZzSQ3rMIVqV/UFUpb/S32SU+AlVMICWRnB8FseYUiJl2PN7D7PZ9J6lugNETIV6VTaKu2xG+QxpzRWQnOSP7QHpDJYYKMjbDuPhAfKozVN7W2W2idz9oFUGDaMYokjSGbMLMRxMFySNXB7Ol5UDF4LNyPS+fqGFSrbbGB/JQuaU1omZu/tipLnsM=
